### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/damage-assessment-bot#94] opened 2018-09-18 15:38 UTC
- [ ] Document steps for development
- [ ] Document steps for production

**Comment by blueelvis** [comment] 2018-09-20 09:55
@dalekunce - When you say document steps for production, do you mean the deployment steps across all the environments?

**Comment by dalekunce** [comment] 2018-09-20 12:15
yes deployment stuff like ```npm install``` and any configuration that needs to happen.

**Comment by m4thfr34k** [comment] 2018-11-13 15:18
Closing due to this being a duplicate of the linked stories. #23 #118

**Closed by m4thfr34k** 2018-11-13 15:18 UTC
